services:
    _defaults:
        autowire: false
        autoconfigure: false

    tiriel.firestore_security.user_provider:
        class: Tiriel\FirestoreSecurityBridge\Security\Provider\FirestoreUserProvider
